# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logLikMk_C <- function(n_nodes, n_tips, n_states, edge_len, edge_mat, parents, X, Q, root_node, root_type) {
    .Call('_CorrSeq_logLikMk_C', PACKAGE = 'CorrSeq', n_nodes, n_tips, n_states, edge_len, edge_mat, parents, X, Q, root_node, root_type)
}

